[package]
name = "rust-elements-wrapper"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_elements_wrapper"
crate-type = ["staticlib", "cdylib"]

[dependencies]
elements = { version = "0.22", features = ["serde"] }
hex = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
